---

variables:
  # Generic variables - you usually don't need to override these
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_HOST: tcp://127.0.0.1:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "${DOCKER_TLS_CERTDIR}/client"

stages:
  - build

olip-base-image:
  stage: build
  tags:
    - k8s
  image: ubuntu:xenial
  before_script:
    - apt-get update
    - apt-get install -y coreutils quilt parted qemu-user-static debootstrap zerofree zip dosfstools libarchive-tools libcap2-bin grep rsync xz-utils file git curl bc qemu-utils kpartx gpg xxd kmod
    - echo "IMG_NAME=ideascube-$CI_COMMIT_BRANCH" >> ./config
  script:
    - ./build.sh
  artifacts:
    paths:
      - deploy/*.zip
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        BUILD_VERSION: latest
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CI_COMMIT_BRANCH != "develop"
      variables:
        BUILD_VERSION: testing
    - if: $CI_COMMIT_BRANCH == "develop"
      variables:
        BUILD_VERSION: develop