---

variables:
  # Generic variables - you usually don't need to override these
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_HOST: tcp://127.0.0.1:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "${DOCKER_TLS_CERTDIR}/client"
  DOCKER_VERSION: 20.10.7

stages:
  - build

olip-base-image:
  stage: build
  tags:
    - k8s
  image: docker:${DOCKER_VERSION}
  services:
    - name: docker:${DOCKER_VERSION}-dind
      command: ["--experimental"]
  script:
    - ./build-docker.sh
  artifacts:
    paths:
      - deploy/*.zip