version: "3.9"
services:
  httpd:
    container_name: base-httpd
    image: "ghcr.io/offspot/base-httpd:1.0"
    pull_policy: never
    read_only: true
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: /boot/offspot.yaml
        target: /var/www/offspot.yaml
        read_only: true
