--- pigen/Dockerfile	2022-05-24 16:22:49.000000000 +0000
+++ tree/Dockerfile	2022-05-25 11:39:32.000000000 +0000
@@ -5,7 +5,7 @@
 
 RUN apt-get -y update && \
     apt-get -y install --no-install-recommends \
-        git vim parted \
+        git vim parted exfatprogs exfat-fuse lsb-release \
         quilt coreutils qemu-user-static debootstrap zerofree zip dosfstools \
         libarchive-tools libcap2-bin rsync grep udev xz-utils curl xxd file kmod bc\
         binfmt-support ca-certificates qemu-utils kpartx fdisk gpg pigz\
